### ISSUE TITLE
CSS not displaying properly on IE11

### ISSUE THREAD

**Issue by randomhammer** [getgrav/grav-skeleton-rtfm-site#7]
I unfortunately need to support Grav in a corporate environment using IE11 as the default browser. Sites using the rtfm skeleton do not display properly on IE, no matter what the compatibility settings are. It displays just fine on FireFox and Chrome. 

The admin panel displays just fine in IE11. Is it difficult to get this team to display in IE?

![grav-screenshot](https://cloud.githubusercontent.com/assets/12021759/24150535/f8dd1e38-0e13-11e7-974a-969c12dd2a6d.png)

**Comment by randomhammer** [comment]
Update: The rtfm demo site works just fine in IE11, so something is different between my site and the demo site. Will things break if I do not have a logo?

**Comment by rhukster** [comment]
a logo change shouldn't break the theme.  I really can't say what modifications you have made, and what those changes have broken.  This doesn't sound like a a problem with the RTFM skeleton itself, but more in your modifications.

maybe try making the modifications again to a fresh copy one at a time while testing in IE11 and seeing what you are doing that breaks it?

**Comment by randomhammer** [comment]
I made no modifications at all. None. Unzipped the skeleton in my Apache directory and pointed a browser at it. Not just me, got three other people to test it and it fails to display properly on all of them. I only mentioned the logo because there is a logo on the demo site but does not appear to be one in the skeleton.

I'll try looking at compatibility settings tomorrow, maybe I can narrow it down to something that we do at work. I never touch Windows at the house, so I can't test things here.

On Mar 21, 2017, 11:33 AM -0500, Andy Miller <notifications@github.com>, wrote:

a logo change shouldn't break the theme. I really can't say what modifications you have made, and what those changes have broken. This doesn't sound like a a problem with the RTFM skeleton itself, but more in your modifications.

maybe try making the modifications again to a fresh copy one at a time while testing in IE11 and seeing what you are doing that breaks it?

**Comment by KoreMike** [comment]
I am also having a problem with IE 11. The menu CSS is delayed for each page load. This problem does not occur with Edge, Chrome or Firefox
