### ISSUE TITLE
Escape curly braces in twig

### ISSUE THREAD

**Issue by KoreMike** [getgrav/grav-skeleton-rtfm-site#9]
I have an issue with using twig site variables from site.yaml

Any pages which contain curly braces in code blocks are giving a server error.  How can I escape curly braces when using twig with Grav?

**Comment by rhukster** [comment]
So the curly braces are in the page content or the site.yaml variables?

In either case if you have twig processing on these could be confused with twig tags.  You should be able to just wrap the code with twig verbatim tags.

**Comment by flaviocopes** [comment]
(https://twig.sensiolabs.org/doc/2.x/tags/verbatim.html)

**Comment by KoreMike** [comment]
Thanks guys I got it fixed with verbatim tags
